[package]
name = "pandacare-chat-v2"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
futures = "0.3.31"
jsonwebtoken = "9.3.1"
mongodb = "3.2.3"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.0", features = ["macros", "tokio-macros"] }
